### ISSUE TITLE
Invalid subcommands throw AIOOB exception

### ISSUE THREAD

**Issue by DrZoddiak** [ipsk/MattFrameworkJDA#4]
**What is the issue?**
When invalid subcommands are ran An ArrayIndexOutofBoundsException is thrown

**What is expected to happen?**
The exception properly handled, and possibly a message sent back that an invalid sub-command was issued

**Versions**
`     net.dv8tion:JDA:4.1.1_165`
    `me.mattstudios.utils:matt-framework-jda:1.1.10-BETA`

**Code snippet**
https://gist.github.com/DrZoddiak/fc97f4b823a8db57822e99a0069744f0

**Reproduction steps**
`!stuff` it runs default as expected
`!stuff otherStuff` it runs as expected
`!stuff beans` it throws an AIOOB exception

**Comment by ipsk** [comment]
Fixed for version `1.1.11-BETA` - 2fc68f3
