### ISSUE TITLE
Base commands shouldn't send back "Command doesn't exist" by default

### ISSUE THREAD

**Issue by DrZoddiak** [ipsk/MattFrameworkJDA#6]
**What is the issue?**
The issue we're noticing is that sometimes can conflict if the prefix is the same
For example:
MEE6 uses `!` as it's prefix so If I were to run a command from MEE6 that my bot didn't have we end up with the expected output, and a message from my bot about the command not existing.

**What is expected to happen?**
Ideally the message doesn't send an error at all, or if at all, it's an optional specified when adding (similar to how prefix is specified, but as a boolean value)

**Versions**
net.dv8tion:JDA:4.1.1_165
me.mattstudios.utils:matt-framework-jda:1.1.14-BETA

**Reproduction steps**
Have a bot with same prefix as your bot
Run command from other bot
See result

**Visual**
https://i.imgur.com/uzdo1vI.png

**Comment by ipsk** [comment]
Yeah I encountered the same problem while working on it.
You can disable the message though, doing something like `commandManager.registerMessage("cmd.no.exists") {}`.

**Comment by DrZoddiak** [comment]
Works great, thank you so much!
